### Get locations form lng, lat within radius with limit
GET {{localhost}}:{{port}}/api/search?lng=9.993470&lat=53.702139&radius=1000&limit=20

### Get addresses from autocomplete
GET {{localhost}}:{{port}}/api/autocomplete?query=Berlin